name: everything_data_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=1.4
  - numpy>=1.22
  - scikit-learn>=1.1
  - matplotlib>=3.5
  - seaborn>=0.12
  - catboost>=1.0
  - imbalanced-learn>=0.9
  - joblib>=1.2
  - jupyterlab
  - notebook
  - python-pptx
  - openpyxl
