
random_state: 42
test_size: 0.2
cv_folds: 5
target_col: "Graduation status"
drop_columns:
  - "Timestamp"
  - "ID No."
  # Optionally drop if considered data leaks at prediction time:
  # - "Total score"
numeric_cols:
  - "Years of learning experience in the data field"
  - "Hours per week available"
  - "Total score"
categorical_cols:
  - "Age range"
  - "Gender"
  - "Country"
  - "Where did you hear about Everything Data?"
  - "Track applied for"
  - "Main aim for joining"
  - "Motivation for joining"
  - "Self-assessed skill level in chosen track"
  - "Aptitude test completion status"
models:
  - name: "log_reg"
    type: "logistic_regression"
    params:
      C: 1.0
      max_iter: 1000
  - name: "random_forest"
    type: "random_forest"
    params:
      n_estimators: 400
      max_depth: null
      min_samples_leaf: 2
      n_jobs: -1
metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1"
